site_name: rick 的笔记本
repo_url: https://github.com/rick-368/Notebook
repo_name: rick/Notebook
theme:
  name: material
  icon:
    logo: material/cat # 页面左上角的图标
  language: zh # 语言

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch 
        name: 天黑请闭眼

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: 天亮请睁眼

  features:
      #- navigation.instant # 现在页面不会跳转,而是类似单页应用,搜索和各种跳转都是在当前页面完成,对美观有很大帮助
      - navigation.tabs # 页面上方的标签页
      - navigation.tracking # 页面滚动时，导航栏高亮当前页面
      - navigation.sections # 使导航栏分块
      - navigation.prune # 只渲染当前页面的导航
      - navigation.top # 返回顶部按钮
      - search.suggest # 补全建议
      - search.highlight # 搜索结果高亮
      - search.share # 搜索结果分享
      - navigation.footer # 页脚提示下一章
      - content.code.copy # 代码段上的赋值按钮
      - navigation.indexes  # 关键特性：支持索引页面
      - navigation.expand  # 关键特性：支持展开子目录
  
nav:
  - 前言: index.md
  - 计算机科学:
    - 高级数据结构与算法分析: 
      - 计算机科学/高级数据结构与算法分析/index.md
      - 树: 计算机科学/高级数据结构与算法分析/chapter1.md
      - 摊还分析: 计算机科学/高级数据结构与算法分析/chapter2.md
      - 堆: 计算机科学/高级数据结构与算法分析/chapter3.md
      - 基本算法（回溯、分治、动态规划）: 计算机科学/高级数据结构与算法分析/chapter4.md
      - 贪心算法: 计算机科学/高级数据结构与算法分析/chapter5.md
      - P与NP: 计算机科学/高级数据结构与算法分析/chapter6.md
      - 近似算法: 计算机科学/高级数据结构与算法分析/chapter7.md
      - 局部搜索: 计算机科学/高级数据结构与算法分析/chapter8.md
      - 随机算法: 计算机科学/高级数据结构与算法分析/chapter9.md
      - 并行算法: 计算机科学/高级数据结构与算法分析/chapter10.md
      - 外部排序: 计算机科学/高级数据结构与算法分析/chapter11.md

    - 计算机系统Ⅱ:
      - 计算机科学/计算机系统2/index.md
      - 进程: 计算机科学/计算机系统2/chapter1.md
      - CPU调度: 计算机科学/计算机系统2/chapter2.md
      - 进程间通信: 计算机科学/计算机系统2/chapter3.md
      - 线程: 计算机科学/计算机系统2/chapter4.md
      - 同步: 计算机科学/计算机系统2/chapter5.md

    - 计算机系统Ⅲ:
      - 计算机科学/计算机系统3/index.md
      - 量化研究: 计算机科学/计算机系统3/chapter1.md
      - ISP: 计算机科学/计算机系统3/chapter2.md
      - Memory Hierarchy: 计算机科学/计算机系统3/chapter3.md
      - 内存: 计算机科学/计算机系统3/chapter4.md
      - 大容量存储结构: 计算机科学/计算机系统3/chapter5.md
      - I/O设备管理: 计算机科学/计算机系统3/chapter6.md
      - 文件系统: 计算机科学/计算机系统3/chapter7.md
      - 系统安全: 计算机科学/计算机系统3/chapter8.md
      - SIMD: 计算机科学/计算机系统3/chapter9.md
      - MIMD: 计算机科学/计算机系统3/chapter10.md

    - 人工智能引论: 
      - 计算机科学/人工智能引论/index.md
      - 知识表达与推理: 计算机科学/人工智能引论/chapter1.md
      - 搜索探寻与问题求解: 计算机科学/人工智能引论/chapter2.md
      - 机器学习: 计算机科学/人工智能引论/chapter3.md
      - 神经网络与深度学习: 计算机科学/人工智能引论/chapter4.md
      - 强化学习: 计算机科学/人工智能引论/chapter5.md
      - 博弈论: 计算机科学/人工智能引论/chapter6.md
      - 人工智能伦理与安全: 计算机科学/人工智能引论/chapter7.md

    - 面向对象程序设计:
      - 计算机科学/面向对象程序设计/index.md
      - C++基础: 计算机科学/面向对象程序设计/chapter1.md
      - 容器: 计算机科学/面向对象程序设计/chapter2.md
      - 结构与类: 计算机科学/面向对象程序设计/chapter3.md
      - 函数复用: 计算机科学/面向对象程序设计/chapter4.md
      - 异常: 计算机科学/面向对象程序设计/chapter5.md
      - C++的输入输出: 计算机科学/面向对象程序设计/chapter6.md
      - Cast 运算符: 计算机科学/面向对象程序设计/chapter7.md

    - 数据库系统:
      - 计算机科学/数据库系统/index.md
      - 数据库介绍: 计算机科学/数据库系统/chapter1.md
      - 关系模型: 计算机科学/数据库系统/chapter2.md
      - SQL 语言基础: 计算机科学/数据库系统/chapter3.md
      - 进阶SQL: 计算机科学/数据库系统/chapter4.md
      - Entitiy-Relationship Model: 计算机科学/数据库系统/chapter5.md
      - 关系型数据库设计: 计算机科学/数据库系统/chapter6.md
      - 存储和文件结构: 计算机科学/数据库系统/chapter7.md
      - 索引和哈希: 计算机科学/数据库系统/chapter8.md
      - 查询处理: 计算机科学/数据库系统/chapter9.md
      - 事务: 计算机科学/数据库系统/chapter10.md
      - 并发控制: 计算机科学/数据库系统/chapter11.md
      - 恢复系统: 计算机科学/数据库系统/chapter12.md


  - 数理基础:
    - 概率论与数理统计:
      - 数理基础/概率论与数理统计/index.md
      - 随机事件和概率: 数理基础/概率论与数理统计/chapter1.md
      - 随机变量及其概率分布: 数理基础/概率论与数理统计/chapter2.md
      - 多维随机变量: 数理基础/概率论与数理统计/chapter3.md
      - 随机变量的数字特征: 数理基础/概率论与数理统计/chapter4.md
      - 大数定律: 数理基础/概率论与数理统计/chapter5.md
      - 统计与抽样分布: 数理基础/概率论与数理统计/chapter6.md
      - 估计: 数理基础/概率论与数理统计/chapter7.md
      - 假设检验: 数理基础/概率论与数理统计/chapter8.md
    - 普通物理学二: 
      - 数理基础/普通物理学2/index.md
      - 电势: 数理基础/普通物理学2/chapter2.md
      - 导体: 数理基础/普通物理学2/chapter3.md
      - 电阻和电容: 数理基础/普通物理学2/chapter4.md
      - 电路: 数理基础/普通物理学2/chapter5.md
      - 磁场: 数理基础/普通物理学2/chapter6.md
      - 电流的磁场: 数理基础/普通物理学2/chapter7.md
      - 磁性材料: 数理基础/普通物理学2/chapter8.md
      - 法拉第电磁感应定律: 数理基础/普通物理学2/chapter9.md
      - 电感: 数理基础/普通物理学2/chapter10.md
      - LC振荡电路: 数理基础/普通物理学2/chapter11.md
      - 麦克斯韦方程组与电磁波: 数理基础/普通物理学2/chapter12.md
      - 光: 数理基础/普通物理学2/chapter13.md
      - 期中复习: 数理基础/普通物理学2/chapter14.md
      - 几何光学: 数理基础/普通物理学2/chapter15.md
      - 光的干涉: 数理基础/普通物理学2/chapter16.md
      - 衍射: 数理基础/普通物理学2/chapter17.md 
      - 光栅与光谱: 数理基础/普通物理学2/chapter18.md
      - 光的偏振: 数理基础/普通物理学2/chapter19.md
      - 光的量子性: 数理基础/普通物理学2/chapter20.md
      - 电磁辐射的量子性: 数理基础/普通物理学2/chapter21.md
      - 物质波: 数理基础/普通物理学2/chapter22.md
      - 薛定谔方程和量子隧穿: 数理基础/普通物理学2/chapter23.md
      - 量子阱（Quantum Wells）: 数理基础/普通物理学2/chapter24.md
      - 氢原子模型: 数理基础/普通物理学2/chapter25.md
      - 电子的角动量和自旋: 数理基础/普通物理学2/chapter26.md

  - 课外拓展:
    - markdown: 课外拓展/01-markdown/markdown_basic_grammar.md
    - the missing semester: 
      - 课外拓展/02-the missing semester/index.md
      - Shell: 课外拓展/02-the missing semester/01-Shell.md
      - Data Wrangling: 课外拓展/02-the missing semester/02-Data_wrangling.md
      - Vim: 课外拓展/02-the missing semester/03-Vim.md
      - Git: 课外拓展/02-the missing semester/04-Git.md
      - Debugging&Profiling: 课外拓展/02-the missing semester/05-Debugging&Profiling.md
      - Metaprogramming: 课外拓展/02-the missing semester/06-Metaprogramming.md
      - Security and Cryptography: 课外拓展/02-the missing semester/07-Security and Cryptography.md
      - MKDoc: 课外拓展/02-the missing semester/08-MKDoc.md
    - CS61A:
      - 课外拓展/03-CS61A/index.md
      - python基础: 课外拓展/03-CS61A/01-python.md
      - 递归: 课外拓展/03-CS61A/02-python.md
      - 序列: 课外拓展/03-CS61A/03-python.md
      - 迭代器与生成器: 课外拓展/03-CS61A/04-python.md
      - 类: 课外拓展/03-CS61A/05-python.md
      - 效率提升与异常处理: 课外拓展/03-CS61A/06-python.md
      - Python 补充: 课外拓展/03-CS61A/07-python.md
      - Scheme 基础: 课外拓展/03-CS61A/08-scheme.md
      - scheme 进阶: 课外拓展/03-CS61A/09-scheme.md
      - SQL: 课外拓展/03-CS61A/10-SQL.md
    - CS61B:
      - 课外拓展/04-CS61B/index.md
      - Java基础: 课外拓展/04-CS61B/01-Java.md
      - 类: 课外拓展/04-CS61B/02-Java.md
      - 数据类型: 课外拓展/04-CS61B/03-Java.md
      - 列表: 课外拓展/04-CS61B/04-Java.md
  - 其他:
    - 无线网络应用:
      - 其他/无线网络应用/index.md
      - 协议和模型: 其他/无线网络应用/chapter1.md
      - 网络通信: 其他/无线网络应用/chapter2.md
      - 通过ISP连接到Internet: 其他/无线网络应用/chapter3.md
      - 网络寻址: 其他/无线网络应用/chapter4.md
      - 无线技术: 其他/无线网络应用/chapter5.md
      - 基本网络安全: 其他/无线网络应用/chapter6.md


  
markdown_extensions:
  - pymdownx.highlight:  # 代码高亮
        anchor_linenums: true
  - admonition # 警告语法
  - def_list
  - footnotes
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex: # latex支持
          generic: true
  - toc:
          permalink: true # 固定标题位置为当前位置
          toc_depth: 3 # 目录深度
  - pymdownx.highlight: # 代码块高亮
          anchor_linenums: true
          linenums: true # 显示行号
          use_pygments: true # 代码高亮
          pygments_lang_class: true
          auto_title: true # 显示编程语言名称
          linenums_style: pymdownx-inline # 行号样式,防止复制的时候复制行号
  - pymdownx.betterem # 强调美化,比如**text**会被美化
  - pymdownx.caret # 上标和下标
  - pymdownx.mark # 上标和下标
  - pymdownx.tilde # 上标和下标
  - pymdownx.keys # 显示按键组合
  - pymdownx.critic
  - pymdownx.details # 可以折叠的代码块 ??? note 可以让警告变成折叠的
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink # 自动识别链接
  - pymdownx.smartsymbols # 智能符号
  - pymdownx.snippets # 代码段
  - pymdownx.tasklist:
        custom_checkbox: true # 自定义复选框
  - attr_list
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences: # 代码块中支持Mermaid
        custom_fences: # 支持 Mermaid
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
          alternate_style: true
          combine_header_slug: true
  - pymdownx.tasklist:
          custom_checkbox: true
          clickable_checkbox: true
  - meta # 支持Markdown文件上方自定义标题标签等
  - tables

extra_javascript:
    - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - javascripts/math-config.js
    - javascripts/math-fix.js 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rick-368/Notebook